<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20250505104023 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return 'Handle DBAL breaking change (v2 -> v3) - CHANGE COMMENT type "json_array" to "flow_json_array"';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf(!($this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform), 'Migration can only be executed safely on "mysql".');

        // TODO: doctrine crashes because of unsupported type "json_array" in Version20160524125855.php before this can be applied.
        // $this->addSql("ALTER TABLE sandstorm_usermanagement_domain_model_registrationflow MODIFY COLUMN attributes LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
        $this->addSql("ALTER TABLE sandstorm_usermanagement_domain_model_registrationflow CHANGE attributes attributes LONGTEXT NOT NULL COMMENT '(DC2Type:flow_json_array)'");
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf(!($this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform), 'Migration can only be executed safely on "mysql".');

        $this->addSql("ALTER TABLE sandstorm_usermanagement_domain_model_registrationflow CHANGE attributes attributes LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)'");
    }
}
